services:
  mongo:
    image: mongo:latest
    platform: linux/amd64
    container_name: mongo
    ports:
      - "2017:27017"

  app:
    build:
      context: .
    platform: linux/amd64
    container_name: app
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongo:27017/ipets
    depends_on:
      - mongo

  portainer:
    image: portainer/portainer-ce
    platform: linux/amd64
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    restart: always

volumes:
  portainer_data: